import Image from 'next/image';
import React from 'react';

export default function FilmLogs() {
  return (
    <div className="w-full my-14 border-y">
      <div className="flex flex-col items-center mx-1 sm:px-0">
        <h2 className="mt-10 mb-10 pb-3 text-4xl text-center border-b">
          FilmLog - FAX TRANSMISSION REPORT
        </h2>

        <dl className="grid grid-cols-1 lg:grid-cols-[60px_1fr] gap-x-6 gap-y-1 lg:gap-y-2 leading-relaxed text-18 w-[310px] sm:w-[400px] md:w-[540px] mx-2">
          <dt className="text-18">PROJECT</dt>
          <dd className="font-sans text-14">FilmLogs</dd>

          <dt className="text-18">PERIOD</dt>
          <dd className="font-sans text-14">2025.11.24 ~ 2025.12.02</dd>

          <dt className="text-18">TYPE</dt>
          <dd className="font-sans text-14">개인 프로젝트</dd>

          <dt className="text-18">STACK</dt>
          <dd className="md:w-[460px] font-sans text-14">
            React Native · Expo · TypeScript · NativeWind Supabase · React Query
            · react-native-modal · react-native-image-picker ·
            react-native-star-rating-widget ·
            react-native-keyboard-aware-scroll-view
          </dd>
        </dl>
      </div>

      <div className="w-full flex flex-col items-center ">
        <hr className="w-full h-[1px] mt-10 bg-[repeating-linear-gradient(to_right,#737373_0_10px,transparent_10px_13px)] border-none" />
        <div className="w-[310px] sm:w-[400px] md:w-[540px] mx-2">
          <p className="pt-3 pb-1 text-18">LINKS :</p>

          <dl className="grid sm:grid-cols-[140px_1fr] gap-x-3 gap-y-1 font-sam text-18 leading-[1.9] tracking-[0.02em] ">
            <dt>DEPLOYMENT :</dt>
            <dd>
              <a
                href="https://expo.dev/artifacts/eas/xfwNQeDD3xYxyCxt99mHNf.apk"
                download
                className="underline hover:text-blue-600 break-all"
              >
                https://expo.dev/artifacts/eas/xfwNQeDD3xYxyCxt99mHNf.apk
              </a>
            </dd>

            <dt>TEST ACCOUNT :</dt>
            <dd>
              ID : test@gmail.com <br />
              PW : test1234
            </dd>

            <dt>GITHUB :</dt>
            <dd>
              <a
                href="https://github.com/yuhyeon9808/FilmLogs"
                target="_blank"
                rel="noopener noreferrer"
                className="underline hover:text-blue-600 break-all"
              >
                https://github.com/yuhyeon9808/FilmLogs
              </a>
            </dd>
          </dl>
        </div>
      </div>

      <div className="w-full flex flex-col items-center">
        <hr className="w-full h-[1px] mt-3 bg-[repeating-linear-gradient(to_right,#737373_0_10px,transparent_10px_13px)] border-none" />
        <div className="w-[310px] sm:w-[400px] md:w-[540px] mx-2">
          <p className="pt-3 pb-1 text-18">MESSAGE :</p>
          <p className="font-sans text-14 leading-[1.9] tracking-[0.02em]">
            FilmLogs는 감상한 영화를 간단히 기록하고 모아볼 수 있는 개인 영화
            리뷰 앱입니다제목, 포스터, 평점, 명대사, 한 줄 감상을 빠르게 남길 수
            있어 가볍게 아카이브할 수 있습니다. 모든 기록은 검색과 별점
            필터링으로 손쉽게 찾아볼 수 있으며, 필요한 정보만 담아낸 단순하고
            직관적인 흐름을 통해 ‘보고, 기록하고, 다시 꺼내보는 경험’을
            자연스럽게 이어줍니다.
          </p>
        </div>
      </div>

      <div className="w-full flex flex-col items-center">
        <hr className="w-full h-[1px] mt-3 bg-[repeating-linear-gradient(to_right,#737373_0_10px,transparent_10px_13px)] border-none" />
        <div className="w-[310px] sm:w-[400px] md:w-[540px] mx-2">
          <p className="pt-3 pb-1 text-18">FEATURES :</p>
          <ul className="font-sans text-14 leading-[2.3] tracking-[0.02em] pb-3">
            <li>□ 영화 리뷰 목록 조회 </li>
            <li>□ 리뷰 추가 · 수정 · 삭제</li>
            <li>□ 별점 기반 필터링</li>
            <li>□ 리뷰 검색</li>
          </ul>
        </div>
      </div>

      <div className="w-full flex flex-col items-center pb-3">
        <hr className="w-full h-[1px] bg-[repeating-linear-gradient(to_right,#737373_0_10px,transparent_10px_13px)] border-none" />
        <div className="w-[310px] sm:w-[400px] md:w-[540px] mx-2 pb-3">
          <p className="pt-3 pb-1 text-18">ATTACHED FILES :</p>

          <div className="relative mx-auto mt-3 h-[310px] w-[310px] sm:w-[400px] md:w-[540px] bg-[#0D0D0D] flex items-center justify-center">
            <Image
              src="/filmLogs/FilmLogs.png"
              alt="필름로그 목업"
              className="object-contain"
              width={290}
              height={290}
            />
          </div>
        </div>
        <hr className="w-full h-[1px] mt-3 bg-[repeating-linear-gradient(to_right,#737373_0_10px,transparent_10px_13px)] border-none" />
      </div>

      <div className="w-full flex flex-col items-center">
        <p className="w-[310px] sm:w-[400px] md:w-[540px] mx-2 py-3 text-18">
          NOTE : This report was automatically generated by Hyeonji OS Fax
          Driver v1.3
        </p>
      </div>
    </div>
  );
}
