import Image from 'next/image';
import React from 'react';

export default function Qmate() {
  return (
    <div className="border-y my-14 w-full">
      <div className="flex flex-col items-center mx-1 sm:px-0">
        <h2 className="text-center mt-10 pb-3 mb-10 text-4xl border-b ">
          FAX TRANSMISSION REPORT
        </h2>

        <dl
          className="grid lg:grid-cols-[100px_1fr] gap-x-6 lg:gap-y-2 text-18 leading-relaxed   grid-cols-1 gap-y-1 w-[310px] sm:w-[400px] md:w-[540px] mx-2
"
        >
          <dt>PROJECT</dt>
          <dd>Q-mate</dd>

          <dt>PERIOD</dt>
          <dd>2025.09 ~ 2025.10</dd>

          <dt>TEAM</dt>
          <dd>Frontend 2 · Backend 3</dd>

          <dt>ROLE</dt>
          <dd className="font-gal text-14">
            로그인 · 테마 · 매칭 플로우 · 커스텀 질문 · 디자인 · 영상편집
          </dd>

          <dt>STACK</dt>
          <dd className="md:w-[460px]">
            Next.js · TypeScript · Tailwind CSS · Shadcn/ui · React Query ·
            Zustand · Axios · Motion · Web API
          </dd>

          <dt>DEPLOYMENT</dt>
          <dd>
            <a
              href="https://q-mate.vercel.app"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Q-mate 배포 사이트 방문"
              className="underline hover:text-blue-600"
            >
              https://q-mate.vercel.app
            </a>
          </dd>

          <dt>DOCS</dt>
          <dd>
            <a
              href="https://buly.kr/BeLEiFS"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Q-mate 노션 문서 방문"
              className="underline hover:text-blue-600"
            >
              https://buly.kr/BeLEiFS
            </a>
          </dd>

          <dt>GITHUB</dt>
          <dd>
            <a
              href="https://github.com/Sua90827/q-mate"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Q-mate 깃허브 방문"
              className="underline hover:text-blue-600"
            >
              https://github.com/Sua90827/q-mate
            </a>
          </dd>
        </dl>
      </div>
      <div className="w-full flex flex-col items-center">
        <hr className="w-full h-[1px] mt-10   bg-[repeating-linear-gradient(to_right,#737373_0_10px,transparent_10px_13px)] border-none" />

        <div className="w-[310px] sm:w-[400px] md:w-[540px] mx-2">
          <p className="w-full  pt-3 pb-1  text-18">MESSAGE :</p>
          <p className=" leading-[1.9] tracking-[0.02em] font-gal text-14">
            Q-mate는 1:1 매칭 기반의 데일리 Q&A 서비스로, 두 사용자가 같은
            질문에 답변하고, 모두 제출을 완료해야 서로의 답을 열람할 수
            있습니다. 이 ‘동시 공개’ 구조는 기다림을 경험으로 전환하고, 답변이
            교차하는 순간에 몰입을 유도합니다.
          </p>
        </div>
      </div>
      <div className="w-full flex flex-col items-center">
        <hr className="w-full h-[1px] mt-3 bg-[repeating-linear-gradient(to_right,#737373_0_10px,transparent_10px_13px)] border-none" />
        <div className="w-[310px] sm:w-[400px] md:w-[540px] mx-2">
          <p className="w-full  pt-3 pb-1 x text-18">FEATURES :</p>
          <ul className="font-gal text-14 leading-[2.5] tracking-[0.02em] pb-3">
            <li>□ 1대1 연결</li>
            <li>□ 오늘의 질문 & 커스텀 질문</li>
            <li>□ 캘린더</li>
            <li>□ 시간대 별 테마</li>
            <li>□ 캐릭터 성장 시스템</li>
          </ul>
        </div>
        <hr className="w-full h-[1px] bg-[repeating-linear-gradient(to_right,#737373_0_10px,transparent_10px_13px)] border-none" />
      </div>
      <div className="w-full flex flex-col items-center">
        <div className="w-[310px] sm:w-[400px] md:w-[540px] mx-2">
          <p className="w-full  pt-3 pb-1  text-18">ATTACHED FILES :</p>

          <div
            className="
    w-[310px] sm:w-[400px] md:w-[540px] mx-auto relative h-[310px] bg-[#70C2E3]
flex items-center justify-center mt-3
  "
          >
            <Image
              src="/qmate/qmate_phone2.png"
              alt="큐메이트 목업"
              className=" object-contain"
              width={310}
              height={310}
            />
          </div>
          <p className="py-3 text-18"> STATUS : TRANSMITTED SUCCESSFULLY</p>
        </div>
        <hr className="w-full h-[1px] bg-[repeating-linear-gradient(to_right,#737373_0_10px,transparent_10px_13px)] border-none" />
        <p className="py-3 text-18 w-[310px] sm:w-[400px] md:w-[540px] mx-2">
          NOTE : This report was automatically generated by Hyeonji OS Fax
          Driver v1.3
        </p>
      </div>
    </div>
  );
}
